### PR TITLE
feat(types) Added TypeScript definitions

### PR DESCRIPTION
**Pull request by 9renpoto**
Added TypeScript support

### CODE REVIEW

**Comment by 9renpoto** [comment]
https://travis-ci.com/9renpoto/react-ticker

**Comment by AndreasFaust** [comment]
Dōmo arigatō for your efforts! I will merge the PR as soon as possible.

**Comment by 9renpoto** [comment]
@AndreasFaust Hi, Please let me know so I can fix any problems 👍

**Comment by AndreasFaust** [comment]
Sorry, that it took me so long. Thank you again. I connected the repository to travis-ci — is this helpful or is there anything I have to do additionally? I don’t use travis-ci myself yet, so I don’t know, how to set it up and why you need it.

**Pull request merged**
